### ISSUE TITLE
Support for 5.6.2

### ISSUE THREAD

**Issue by karnamonkster** [Orange-OpenSource/kibana-xlsx-import#20] opened 2018-09-30 10:01 UTC
Hi,

First of all thanks for this plugin.
Now I was able to install the nice plugin on my Kibana 5.6.2 using the 5.6.5 build by changing the package.json. Installation was successful and restarted the Kibana with the XLSX plugin on my menu.
However i am not able to load any CSV/xlsx files and getting an error.
`Uncaught ReferenceError:XLSX is not defined(../bundles/xlsx-import.bundle.js?v=15543:27)`

I suspect this is cause of the version mismatch, Is there anyway i could run this for the v5.6.2?

Appreciate a needful response.

**Comment by karnamonkster** [comment] 2018-10-01 03:46
Even tried the plugin with Kibana 5.6.5 , still no luck same error.

**Comment by gwintzer** [comment] 2018-10-01 09:27
Hi,
I did the test with a fresh v5.6.5 install, the plugin works fine for me.
So this is not a lack of some required libraries.

Check if you have a `xlsx` dependency in your package.json, and don't forget `npm install` if you work in development mode.

You could also check that it is not a problem with your browser :
`fs and path are modules that are built into NodeJs, maybe they are not available in the browser.`
(found here : https://stackoverflow.com/questions/47186297/uncaught-referenceerror-xlsx-is-not-defined-on-drop-file)

As a last resort, you should try the behaviour with the new version 6.3.2.

**Comment by karnamonkster** [comment] 2018-10-01 09:59
> Hi,
> I did the test with a fresh v5.6.5 install, the plugin works fine for me.
> So this is not a lack of some required libraries.
> 
> Check if you have a `xlsx` dependency in your package.json, and don't forget `npm install` if you work in development mode.
>
I do not have 'xlsx' dependency in my package.json
> 
> You could also check that it is not a problem with your browser :
> `fs and path are modules that are built into NodeJs, maybe they are not available in the browser.`
> (found here : https://stackoverflow.com/questions/47186297/uncaught-referenceerror-xlsx-is-not-defined-on-drop-file)
> 
> As a last resort, you should try the behaviour with the new version 6.3.2.

**Comment by gwintzer** [comment] 2018-10-01 14:44
Indeed :)
In old version, the XLSX library was included directly in the Html template due to a bug with package inclusion...
So could you check if the 3 following scripts are correctly loaded in your network tab from developer tools browser ?
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.11.18/shim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.11.18/xlsx.core.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.11.18/xlsx.full.min.js"></script>
```
Maybe a proxy or something else prevents you to load this scripts...

**Comment by karnamonkster** [comment] 2018-10-03 06:51
Yes these are not loaded since the environment we have does not allow internet access.
Any workarounds to that?

**Comment by karnamonkster** [comment] 2018-10-04 07:01
Just wanted to check, where does the uploaded file gets stored?

**Comment by gwintzer** [comment] 2018-10-04 07:38
I don't know. Probably it is just kept in the browser's cache.

A possible workaround : 
- unzip the plugin package
- download the 3 previous files 
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.11.18/shim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.11.18/xlsx.core.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.11.18/xlsx.full.min.js"></script>
```
- store them in the `public/` directory of plugin
- edit the `public/templates/index.html` file and change the links to the relative path of the downloaded files
<script src="./shim.min.js"></script>
<script src="./xlsx.core.min.js"></script>
<script src="./xlsx.full.min.js"></script>
- rezip all and try

(not tested / just the idea)

or update your project to v6.3 : the xslx dependency is installed on build...

**Comment by gwintzer** [comment] 2018-10-18 14:46
I close the issue.
The problem with v5.2 + no internet access is not reproductible in v6.3+.
The point 1 with () is also not reproductible in v6.3+

For others problems (point 2-3), please create some new issues with more details.

**Closed by gwintzer** 2018-10-18 14:46 UTC
